### PR TITLE
Update to MCP Snapshot 20160421

### PR DESCRIPTION
**Pull request by Craiel**
Not sure if you want to take this or not but i figured i just make a request and see :).

I've been running this locally for a while now, it's working with the very latest Forge 1.9 and MCP

### CODE REVIEW

**Comment by amadornes** [comment]
I should update to the latest mappings, yeah... But all the other changes are completely unrelated to mappings. There's even two deleted methods in BlockCoverable and one in BlockMultipartContainer (entity collision detection in both cases). Also, why update the version in the build.gradle? You should probably leave that to me so jenkins doesn't go crazy and we can keep a stable naming system in maven :P
I get why all the other changes are needed but... why do you need the newer mappings? It's not like much has changed.
I'll look into it myself and push a new update to curse and maven later today :)

**Comment by Craiel** [comment]
No problem i mainly just wanted to check,

the functions i removed where no longer available for override with latest
mdk and mapping and it looks like they where dropped for consistent use of
the calls with IBLockState, at least not for me. I may have missed
something tho.
The version number is just for me but i didnt see how i can exclude files
from pull requests, is there such an option?
I am working with RFTools and DeepResonance and a mod of my own in dev
environment which all are upgraded to the latest mapping and cause of
dependency chain i need the rest of the mods on the same level, most namely
ElecCore, Waila, Jei and MCMultipart in turn.

Anyway sorry for the trouble :)

**Comment by amadornes** [comment]
I'll see what I can do about those missing methods and the extra IBlockStates. It should be fairly easy to fix. About the thing with version numbers... no, there's no way to exclude such a thing from a PR but you can just exclude it from the commit if it's only meant for local use.
Also, if you have a "normal" workspace setup you should be able to add obfuscated dependencies to your buildscript instead of deobf ones so that they work with whatever mappings you're using ;)

**Comment by Craiel** [comment]
Ok great, thanks for the advice

**Comment by amadornes** [comment]
That thing about releasing it today... I think I'll have to do it tomorrow. I didn't get to finish all the things I wanted to do before having to go. I'm sure I'll finish it tomorrow :)

**Comment by Craiel** [comment]
Thats quite alright, thanks for looking into it :)

**Comment by amadornes** [comment]
Well, that commit didn't close it... So I guess I'll do it myself :P

**Pull request closed without merging**
