### PR TITLE
Fix #112

### LINKED ISSUE #112: breakBlock call resets RS nodes
See https://github.com/raoulvdberge/refinedstorage/issues/1576

### PR DESCRIPTION
**Pull request by dblsaiko**
Fixes #112 by setting the new block state (Multipart) into Chunk's storage arrays before calling setBlockState, thus causing it not to call breakBlock on the old block.

### CODE REVIEW

**Comment by asiekierka** [comment]
I'm going to make a suggestion: instead of doing this, have BlockMultipart's breakBlock() a NOP given a special, thread-local flag is set to true. Might be less hacky in practice.

**Comment by asiekierka** [comment]
Wait. Does this involve converting from non-multiparts to multiparts? If so, ignore my suggestion!

Going to propose another one: writeToNBT the tile entity before setting the block state, then readFromNBT it to restore it. This is a bit slower, but guaranteed to avoid setBlockState side effects.

**Comment by dblsaiko** [comment]
Yep, this is for converting into multiparts.

**Comment by raoulvdberge** [comment]
> Going to propose another one: writeToNBT the tile entity before setting the block state, then readFromNBT it to restore it. This is a bit slower, but guaranteed to avoid setBlockState side effects.

That assumes the only use case for this workaround is TE persistance, while breakBlock can do virtually anything (not only TE stuff).

**Comment by asiekierka** [comment]
@raoulvdberge Fair point.

**Pull request merged**
