### PR TITLE
Replaceable parts

### LINKED ISSUE #57: Replaceable parts
I think it'd be useful to have replaceable parts, like tall grass. I'd use it so the top of my catwalks stair block can be replaced with a normal block if all the sides are disabled.

### PR DESCRIPTION
**Pull request by dblsaiko**
This allows some parts to be replaceable, just like vanilla tallgrass blocks, for example. When a new part is placed and all the conflicting parts (same part slot, overlapping occlusion boxes) are replaceable, they will be removed first and then the new part will be added.

Fix #57

### CODE REVIEW

**Comment by asiekierka** [comment]
"@therealfarfetchd requested a review from amadornes on Jan 11"

**Comment by dblsaiko** [comment]
Heh, yeah, ama wanted some changes on this... and I don't know if the guy still needs it since the original issue is from 2016 :')

**Comment by amadornes** [comment]
Oh.

Uh...

I... think I'm a bit late to this...

**Comment by asiekierka** [comment]
~~if you merge it now you might still beat some Fabric pull requests~~

**Pull request closed without merging**
