### PR TITLE
Fix #106

### LINKED ISSUE #106: [1.12.2] - Dissappearing Blocks
I am trying to use MCMultipart with Chisels & Bits to cover some Refined Storage (RS) cables.  When I place the covers I created, they place just fine in the same spaces as the cables.  When I log out and come back in, however, the covers are invisible, along with the RS cables, but the RS systems are still connected.  But, because they are invisible, I cannot break them to replace them.

### PR DESCRIPTION
**Pull request by asiekierka**

### CODE REVIEW

**Comment by dblsaiko** [comment]
Ooooh, this might fix some problems I've been having with Multiparts too..

**Comment by raoulvdberge** [comment]
Thank you asie! Did you test this with RS too by any chance?

**Comment by AlgorithmX2** [comment]
This certainly looks promising.

**Comment by asiekierka** [comment]
@raoulvdberge Tested it *specifically* with RS and C&B, as it was the named reproduction case.

**Comment by raoulvdberge** [comment]
Cool, thanks.

**Pull request merged**
